### PR TITLE
Add support for processing simple commands

### PR DESCRIPTION
**Pull request by choffee**
In order to be able to write a simple interface I am processing commands over mqtt in the server.

This way we can write commands onto mqtt with any UI and not have to fiddle with the game code too much.

This just adds exit and skip_intro commands 

To use it:
`mosquitto_pub -h localhost -t command/exit -m"No real message"`

### CODE REVIEW

**Comment by lexbailey** [comment]
I like it!
I'll probably merge this in tomorrow when i go hack the server.

**Comment by choffee** [comment]
It might be worth testing it first :)

I was trying to get it up and running on my laptop last night but could not get it to do anything. I did have to switch to the paho library for mqtt as I can't find the old mosquitto library any more.

john

**Comment by aquila12** [comment]
I think last time i did anything with it i also needed to adapt it to use
paho. If that's something that isn't in master yet we should probably bite
the bullet, it's mostly the same.

**Comment by choffee** [comment]
Oh and I think I might have missed the client.subsctibe bit for the commands. I may get time over lunch...

**Comment by lexbailey** [comment]
Thanks John, this needed some tweaks, but it's got the command support off the ground. I've got a basic GUI sending commands, I'm going to keep playing around with it today.

**Pull request merged**
